### ISSUE TITLE
timer bell issues

### ISSUE THREAD

**Issue by dsiskind** [Sirimangalo/meditation-plus-angular#129]
I have been using the bird sounds. the bell at the end of walking meditation was truncated. the bell at the end of sitting was silent.

**Comment by binarious** [comment]
Were you using a smartphone or tablet?

**Comment by binarious** [comment]
I've hat that problem this morning, too.
@olastor What do you think about the following idea? We could create a mp3 file clientside for every session with a JavaScript mp3 library. The file would contain silence at the beginning with the length of the walking meditation and then the bell. After this silence again with the length of the sitting meditation and then the bell again. This way the whole session would be an audio stream and should work on every smartphone.

**Comment by olastor** [comment]
That could work. We'd have to see how big such a file gets when adding 30min of silence.

**Comment by olastor** [comment]
Made some tests with audacity:

*60 min. of silence + bell*

- `.mp3`: ~ 15mB
- `.m4a`: ~ 2mB
- `.ogg`: ~ 400kB
- `.wav`: ~ 320mB

`.ogg` definitely has the better compression ratio for that. But it's not [compatible](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats) with Safari and maybe Chrome on mobile as well. :neutral_face:

**Comment by dsiskind** [comment]
I'm using chrome

**Comment by dsiskind** [comment]
Clarification. Using chrome on Windows 10.

**Comment by binarious** [comment]
@olastor Surprised about mp3's big file size since there isn't more entropy. That's not usable. I don't think it's possible to allow a timer that works in the background of a mobile phone. But we could fix the specific problem described in this issue this way: http://stackoverflow.com/a/11973935

**Comment by olastor** [comment]
@binarious Not sure if this will work with Phones in Sleep mode

**Comment by binarious** [comment]
@olastor I don't think it will, but it'll fix the general audio bug (truncated first bell, second bell not ringing).

**Comment by olastor** [comment]
@binarious The truncated problem is already fixed in #126 (should be ...). I'm opening a separate issue for the timer on mobiles.

**Comment by binarious** [comment]
Ok so this one is already fixed there.

**Comment by dsiskind** [comment]
guys. maybe you know this but this is not fixed. tried the birds 12 hours ago and got neither the end of walking nor the final sounds.  And just had a session now after changing to bell1 and got a truncated bell at end of walking and nothing at the end of sitting. This using chrome with windows10. BTW it rings fine (3x) when testing in edit mode on my profile.

**Comment by dsiskind** [comment]
In case it's not clear I'm using a laptop.

**Comment by dsiskind** [comment]
It's not fixed so that I can use it.  Please don't give up. I've written
another note on your closed GitHub #129 with symptoms and the conditions
surrounding my use.

David Siskind

**Comment by olastor** [comment]
@dsiskind It's fixed, but not yet pushed to the Server. It will go online with the next release. Until then you might  consider using an additional Timer.

**Comment by dsiskind** [comment]
thanks - I will be patient.  It's looking good.

David Siskind
