### ISSUE TITLE
Calculation of % of commitment completed appears to be wrong

### ISSUE THREAD

**Issue by bkeevil** [Sirimangalo/meditation-plus-angular#195]
According to my meditation log graph I should have reached 100% of my commitment but it says I have only done 65%.

**Comment by binarious** [comment]
When you've committed to a daily goal, then it's calculated for the last 10 days. Need to change the text at the bottom.

**Comment by bkeevil** [comment]
Oh ok.

**Comment by binarious** [comment]
Fixed by https://github.com/Sirimangalo/meditation-plus-angular/commit/fa8896db73a96e05d1cc8d723b76a2972dc60461

**Comment by bkeevil** [comment]
Na its still not working.  I've got 660 minutes this week, my commitment is 840 minutes per week and it says I've completed 100% of my commitment.
